import '../shared/widgets/game_item.dart';

List<GameItems> allGames = [
  GameItems('assets/images/splashLearn2.png', 'PancMan', [
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
  GameItems('assets/images/splashLearn2.png', 'Tic Tac Toe', [
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
  GameItems('assets/images/splashLearn2.png', 'PancMan', [
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
  GameItems('assets/images/splashLearn2.png', 'PancMan', [
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
  GameItems('assets/images/splashLearn2.png', 'PancMan', [
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
  GameItems('assets/images/splashLearn2.png', 'PancMan', [
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
  GameItems('assets/images/splashLearn2.png', 'PancMan', [
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/soccer_kid_doctor',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
    'https://www.y8.com/games/flappy_ball',
  ]),
];
